export enum OPERATOR_STRING {

  CONTAINS = 'CONTAINS',
  NOT_CONTAINS = 'NOT_CONTAINS',
  IN = 'IN',
  EQUALS = 'EQUALS',
  NOT_EQUALS = 'NOT_EQUALS',
  NOT_STARTS_WITH = 'NOTSTARTS_WITH',
  STARTS_WITH = 'STARTS_WITH'

}
